### ISSUE TITLE
cant make index.html public as showed 

### ISSUE THREAD

**Issue by yaskshelat** [miztiik/AWS-Demos#10]
Hi
As showed in the video the bucket has to be private, however index.html file has to be public. I am unable to make my index.html public. please see snapshot below

![image](https://user-images.githubusercontent.com/36253068/76041948-8188b100-5f21-11ea-8106-87cad330d1cb.png)

can you please suggest why "make public" option is grayed out

**Comment by miztiik** [comment]
This is NOT an issue with the code. Rather feature of S3. Google should help you, Something along the lines - https://aws.amazon.com/s3/features/block-public-access/
