### ISSUE TITLE
How can we get rid of the prefix that is appended to the original filename?

### ISSUE THREAD

**Issue by kribby** [miztiik/AWS-Demos#8]
With reference to the repo titled " setup-pre-signed-s3-urls/"

When one uploads a file called "filename.png" - the filename is amended to some thing like this:

cd3223123_filename.png.

How can we stop this from happening and retain the original "filename.png"

**Comment by miztiik** [comment]
The prefix was designed to avoid "collisions".
If two users are uploading files with the same name, We dont want to overwrite them at the server side.
Moreover(atleast sometime ago) S3 liked randomised key prefixes for scaling performance.

If you need to change it, then you can do it in the lambda python code.
